const cardMeanings = {
  1: { name: "Rider", keywords: "뉴스, 메시지, 방문자, 빠른 움직임, 시작", positive: true },
  2: { name: "Clover", keywords: "행운, 기회, 짧은 행복, 가벼움", positive: true },
  3: { name: "Ship", keywords: "여행, 거리, 무역, 이동, 탐험", positive: true },
  4: { name: "House", keywords: "집, 가족, 안정, 전통, 소속", positive: true },
  5: { name: "Tree", keywords: "건강, 성장, 뿌리, 생명력, 인내", positive: true },
  6: { name: "Cloud", keywords: "불확실성, 혼란, 의심, 모호함", positive: false },
  7: { name: "Snake", keywords: "복잡함, 유혹, 지혜, 배신, 욕망", positive: false },
  8: { name: "Coffin", keywords: "종료, 변화, 질병, 슬픔, 재생", positive: false },
  9: { name: "Bouquet", keywords: "선물, 아름다움, 초대, 감사, 기쁨", positive: true },
  10: { name: "Scythe", keywords: "위험, 갑작스러움, 결단, 수확, 날카로움", positive: false },
  11: { name: "Broom", keywords: "대화, 말다툼, 논쟁, 소통, 소문", positive: false },
  12: { name: "Owls", keywords: "스트레스, 걱정, 불안, 긴장, 소통", positive: false },
  13: { name: "Child", keywords: "새로운 시작, 순수함, 작은 것, 젊음", positive: true },
  14: { name: "Fox", keywords: "속임수, 영리함, 직장, 전략, 주의", positive: false },
  15: { name: "Bear", keywords: "힘, 권위, 재정, 리더십, 보호", positive: true },
  16: { name: "Star", keywords: "희망, 영감, 명확성, 인도, 목표", positive: true },
  17: { name: "Stork", keywords: "변화, 이사, 개선, 이동, 진화", positive: true },
  18: { name: "Dog", keywords: "우정, 충성심, 신뢰, 동반자, 지원", positive: true },
  19: { name: "Tower", keywords: "고립, 권위, 기관, 독립, 경계", positive: false },
  20: { name: "Garden", keywords: "사회, 대중, 행사, 네트워킹, 공개", positive: true },
  21: { name: "Mountain", keywords: "장애물, 지연, 도전, 막힘, 인내", positive: false },
  22: { name: "Crossroad", keywords: "선택, 결정, 대안, 자유, 방향", positive: true },
  23: { name: "Mice", keywords: "손실, 스트레스, 소모, 감소, 걱정", positive: false },
  24: { name: "Heart", keywords: "사랑, 감정, 열정, 관계, 기쁨", positive: true },
  25: { name: "Ring", keywords: "약속, 계약, 연결, 결속, 반복", positive: true },
  26: { name: "Book", keywords: "지식, 비밀, 교육, 발견, 연구", positive: true },
  27: { name: "Letter", keywords: "문서, 메시지, 편지, 소식, 정보", positive: true },
  28: { name: "Man", keywords: "남성, 질문자(남), 논리, 행동", positive: true },
  29: { name: "Woman", keywords: "여성, 질문자(여), 직관, 감정", positive: true },
  30: { name: "Lily", keywords: "평화, 성숙, 지혜, 성, 조화", positive: true },
  31: { name: "Sun", keywords: "성공, 행복, 에너지, 승리, 따뜻함", positive: true },
  32: { name: "Moon", keywords: "감정, 명성, 인정, 로맨스, 직관", positive: true },
  33: { name: "Key", keywords: "해결책, 확실성, 중요함, 열림, 성취", positive: true },
  34: { name: "Fish", keywords: "돈, 풍요, 사업, 가치, 흐름", positive: true },
  35: { name: "Anchor", keywords: "안정성, 지속, 목표, 안전, 확고함", positive: true },
  36: { name: "Cross", keywords: "운명, 부담, 시련, 영적 성장, 카르마", positive: false }
};
